map:
    resource: "@MapBundle/Resources/config/routing.yml"
    prefix:   /

chaya3ni_user:
    resource: "@Chaya3niUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
