services:
#    chaya3ni_user.example:
#        class: Chaya3niUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    authentication.handler.login_success_handler:
                class:  Chaya3niUserBundle\Redirection\LoginSuccessHandler
                arguments:  ['@router', '@security.authorization_checker']
    demo_user.registration_listener:
                class:  Chaya3niUserBundle\EventListener\RegistrationListener
                arguments: []
                tags:
                 - { name: kernel.event_subscriber }
